"""Add premium status to User and create LessonLog model

Revision ID: 143b736c0dea
Revises: 6ea2447d852d
Create Date: 2026-01-13 11:24:59.147275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143b736c0dea'
down_revision = '6ea2447d852d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('teacher_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['tutor_request.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_log')
    # ### end Alembic commands ###
