"""Add shortlisted_teacher_ids to TutorRequest

Revision ID: 24e0563aa53e
Revises: be06c49d7c49
Create Date: 2026-01-11 23:37:45.081065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e0563aa53e'
down_revision = 'be06c49d7c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shortlisted_teacher_ids', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_request', schema=None) as batch_op:
        batch_op.drop_column('shortlisted_teacher_ids')

    # ### end Alembic commands ###
