"""Add verification fields to User model

Revision ID: 4cd05dcf853f
Revises: 24e0563aa53e
Create Date: 2026-01-12 00:22:46.449747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd05dcf853f'
down_revision = '24e0563aa53e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('id_verification_status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('id_verification_status')
        batch_op.drop_column('nin')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
