"""Add status to LessonLog and suspended flag to User

Revision ID: 66bdddfaf54e
Revises: 143b736c0dea
Create Date: 2026-01-13 12:34:08.274226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bdddfaf54e'
down_revision = '143b736c0dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_suspended')

    with op.batch_alter_table('lesson_log', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
