"""Add detailed fields for teacher and parent forms

Revision ID: be06c49d7c49
Revises: 9cc562e64823
Create Date: 2026-01-07 12:52:30.698743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be06c49d7c49'
down_revision = '9cc562e64823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highest_qualification', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('relevant_subjects', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('teaching_experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('teaching_philosophy', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('lesson_planning', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('specialized_methods', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('home_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('guarantor_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('guarantor_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=False))
        batch_op.drop_column('availability')
        batch_op.drop_column('class_levels')
        batch_op.drop_column('subjects')
        batch_op.drop_column('location')

    with op.batch_alter_table('tutor_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('student_age', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('student_grade', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('subjects', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('parent_contact_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('house_address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('schedule', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('learning_goals', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('previous_experience', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('teaching_style_preference', sa.Text(), nullable=True))
        batch_op.drop_column('child_class')
        batch_op.drop_column('preferred_time')
        batch_op.drop_column('preferred_days')
        batch_op.drop_column('location')
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('location', mysql.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('preferred_days', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('preferred_time', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('child_class', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('teaching_style_preference')
        batch_op.drop_column('previous_experience')
        batch_op.drop_column('learning_goals')
        batch_op.drop_column('duration')
        batch_op.drop_column('schedule')
        batch_op.drop_column('house_address')
        batch_op.drop_column('parent_contact_number')
        batch_op.drop_column('subjects')
        batch_op.drop_column('student_grade')
        batch_op.drop_column('student_age')
        batch_op.drop_column('student_name')

    with op.batch_alter_table('teacher_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', mysql.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('subjects', mysql.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('class_levels', mysql.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('availability', mysql.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('is_complete')
        batch_op.drop_column('guarantor_address')
        batch_op.drop_column('guarantor_name')
        batch_op.drop_column('home_address')
        batch_op.drop_column('specialized_methods')
        batch_op.drop_column('lesson_planning')
        batch_op.drop_column('teaching_philosophy')
        batch_op.drop_column('teaching_experience')
        batch_op.drop_column('relevant_subjects')
        batch_op.drop_column('highest_qualification')

    # ### end Alembic commands ###
